### ISSUE TITLE
Using the cache service

### ISSUE THREAD

**Issue by ecovantage** [willgeary/geocoding_with_google_sheets#1]
Hi
Firstly, thanks for sharing the code, it has helped me start down the path of learning Apps Script.

Now, do you have any suggestions on how the cache service could be used to prevent the Script from timing out when reverseGeocoding a few hundred addresses? Or is there a better method? 
I tried to reverseGeocode as a custom function, which I got working, but that also dies "Service invoked too many times"

Thanks

**Comment by willgeary** [comment]
Hi, I would recommend using Google Maps Geocoding API:

https://developers.google.com/maps/documentation/geocoding/intro

You can ping the API for geocoding or reverse geocoding up to 2,500 times per day using a free API key.
